CREATE TABLE [dbo].[Persons_Audit] (
    [AuditID]               INT              IDENTITY (1, 1) NOT NULL,
    [PersonID]              INT              NULL,
    [rowguid]               UNIQUEIDENTIFIER NULL,
    [DateTimeStamp]         SMALLDATETIME    NULL,
    [LastModifiedBy]        NVARCHAR (255)   NULL,
    [PersonTypeID]          INT              NULL,
    [CommunityID]           INT              NULL,
    [LocationID]            INT              NULL,
    [CountyID]              INT              NULL,
    [StatusTypeID]          INT              NULL,
    [DJJIDNum]              NVARCHAR (50)    NULL,
    [FirstName]             NVARCHAR (100)   NULL,
    [LastName]              NVARCHAR (100)   NULL,
    [MiddleName]            NVARCHAR (100)   NULL,
    [Email]                 NVARCHAR (255)   NULL,
    [Title]                 NVARCHAR (100)   NULL,
    [CompanyName]           NVARCHAR (100)   NULL,
    [Salutation]            NVARCHAR (50)    NULL,
    [Honorific]             NVARCHAR (50)    NULL,
    [GenderID]              INT              NULL,
    [SocialSecurityNumber]  NVARCHAR (9)     NULL,
    [DateOfBirth]           DATE             NULL,
    [PrimaryLanguageSpoken] NVARCHAR (50)    NULL,
    [OtherLanguagesSpoken]  NVARCHAR (255)   NULL,
    [Notes]                 NVARCHAR (MAX)   NULL,
    [AuditAction]           NVARCHAR (10)    NULL,
    [AuditDateTime]         SMALLDATETIME    CONSTRAINT [DF_Persons_Audit_AuditDateTime] DEFAULT (getdate()) NULL,
    [AuditUser]             NVARCHAR (250)   NULL,
    [AuditSQLUser]          NVARCHAR (250)   NULL,
    CONSTRAINT [PK_Persons_Audit_1] PRIMARY KEY CLUSTERED ([AuditID] ASC)
);

