CREATE TABLE [dbo].[RiskAssessments_Audit] (
    [AuditID]                INT              IDENTITY (1, 1) NOT NULL,
    [RiskAssessmentID]       INT              NULL,
    [rowguid]                UNIQUEIDENTIFIER NULL,
    [DateTimeStamp]          SMALLDATETIME    NULL,
    [LastModifiedBy]         NVARCHAR (255)   NULL,
    [DateApplied]            SMALLDATETIME    NULL,
    [DateEntered]            SMALLDATETIME    NULL,
    [ParentStatus]           VARCHAR (255)    NULL,
    [FamilyStatus]           VARCHAR (255)    NULL,
    [ReferredBy]             VARCHAR (255)    NULL,
    [RefByOther]             VARCHAR (255)    NULL,
    [AttSkipClass]           BIT              CONSTRAINT [DF_RiskAssessments_Audit_Att_skipclass_1] DEFAULT ((0)) NULL,
    [AttSkipSchool]          BIT              CONSTRAINT [DF_RiskAssessments_Audit_Att_skipschool_1] DEFAULT ((0)) NULL,
    [AttTruant]              BIT              CONSTRAINT [DF_RiskAssessments_Audit_Att_truant_1] DEFAULT ((0)) NULL,
    [AttNotEnrolled]         BIT              CONSTRAINT [DF_RiskAssessments_Audit_Att_notenrolled_1] DEFAULT ((0)) NULL,
    [BehSuspended]           BIT              CONSTRAINT [DF_RiskAssessments_Audit_beh_suspended_1] DEFAULT ((0)) NULL,
    [BehExpelled]            BIT              CONSTRAINT [DF_RiskAssessments_Audit_beh_expelled_1] DEFAULT ((0)) NULL,
    [BehSuspendedPrev]       BIT              CONSTRAINT [DF_RiskAssessments_Audit_beh_suspendedprev_1] DEFAULT ((0)) NULL,
    [BehExpelledPrev]        BIT              CONSTRAINT [DF_RiskAssessments_Audit_beh_expelledprev_1] DEFAULT ((0)) NULL,
    [AcFailingSixMos]        BIT              CONSTRAINT [DF_RiskAssessments_Audit_Ac_failingsixmos_1] DEFAULT ((0)) NULL,
    [AcFailingOnce]          BIT              CONSTRAINT [DF_RiskAssessments_Audit_Ac_failingonce_1] DEFAULT ((0)) NULL,
    [AcFailingMoreThanOnce]  BIT              CONSTRAINT [DF_RiskAssessments_Audit_Ac_failingmorethanonce_1] DEFAULT ((0)) NULL,
    [AcLearningDisabilities] BIT              CONSTRAINT [DF_RiskAssessments_Audit_Ac_learningdisabilities_1] DEFAULT ((0)) NULL,
    [ParControl]             BIT              CONSTRAINT [DF_RiskAssessments_Audit_par_control_1] DEFAULT ((0)) NULL,
    [ParUnclear]             BIT              CONSTRAINT [DF_RiskAssessments_Audit_par_unclear_1] DEFAULT ((0)) NULL,
    [ParFreeTimeWhere]       BIT              CONSTRAINT [DF_RiskAssessments_Audit_par_freetimewhere_1] DEFAULT ((0)) NULL,
    [ParFreeTimeWithWhom]    BIT              CONSTRAINT [DF_RiskAssessments_Audit_par_freetimewithwhom_1] DEFAULT ((0)) NULL,
    [ParProbinSchool]        BIT              CONSTRAINT [DF_RiskAssessments_Audit_par_probinschool_1] DEFAULT ((0)) NULL,
    [HistChildAbuse]         BIT              CONSTRAINT [DF_RiskAssessments_Audit_hist_childabuse_1] DEFAULT ((0)) NULL,
    [HistNeglect]            BIT              CONSTRAINT [DF_RiskAssessments_Audit_hist_neglect_1] DEFAULT ((0)) NULL,
    [HistDCF]                BIT              CONSTRAINT [DF_RiskAssessments_Audit_hist_DCF_1] DEFAULT ((0)) NULL,
    [InfCriminalRecord]      BIT              CONSTRAINT [DF_RiskAssessments_Audit_inf_criminalrecord_1] DEFAULT ((0)) NULL,
    [InfPrisonTime]          BIT              CONSTRAINT [DF_RiskAssessments_Audit_inf_prisontime_1] DEFAULT ((0)) NULL,
    [InfProbation]           BIT              CONSTRAINT [DF_RiskAssessments_Audit_inf_probation_1] DEFAULT ((0)) NULL,
    [SATobacco]              BIT              CONSTRAINT [DF_RiskAssessments_Audit_SA_tobacco_1] DEFAULT ((0)) NULL,
    [SADrugs]                BIT              CONSTRAINT [DF_RiskAssessments_Audit_SA_drugs_1] DEFAULT ((0)) NULL,
    [SACharged]              BIT              CONSTRAINT [DF_RiskAssessments_Audit_SA_charged_1] DEFAULT ((0)) NULL,
    [StealFamily]            BIT              CONSTRAINT [DF_RiskAssessments_Audit_steal_family_1] DEFAULT ((0)) NULL,
    [StealCharged]           BIT              CONSTRAINT [DF_RiskAssessments_Audit_steal_charged_1] DEFAULT ((0)) NULL,
    [RunOnce]                BIT              CONSTRAINT [DF_RiskAssessments_Audit_run_once_1] DEFAULT ((0)) NULL,
    [RunThree]               BIT              CONSTRAINT [DF_RiskAssessments_Audit_run_three_1] DEFAULT ((0)) NULL,
    [RunCurrent]             BIT              CONSTRAINT [DF_RiskAssessments_Audit_run_current_1] DEFAULT ((0)) NULL,
    [GangMember]             BIT              CONSTRAINT [DF_RiskAssessments_Audit_gang_member_1] DEFAULT ((0)) NULL,
    [GangReported]           BIT              CONSTRAINT [DF_RiskAssessments_Audit_gang_reported_1] DEFAULT ((0)) NULL,
    [GangLaw]                BIT              CONSTRAINT [DF_RiskAssessments_Audit_gang_law_1] DEFAULT ((0)) NULL,
    [GangAssociated]         BIT              CONSTRAINT [DF_RiskAssessments_Audit_gang_associated_1] DEFAULT ((0)) NULL,
    [GangAssocRecord]        BIT              CONSTRAINT [DF_RiskAssessments_Audit_gang_assocrecord_1] DEFAULT ((0)) NULL,
    [GangRecord]             BIT              CONSTRAINT [DF_RiskAssessments_Audit_gang_record_1] DEFAULT ((0)) NULL,
    [RelReasonForLeaving]    VARCHAR (255)    NULL,
    [RelAgency]              VARCHAR (255)    NULL,
    [RelDate]                SMALLDATETIME    NULL,
    [SSNumberDays]           INT              NULL,
    [SSPossibleDays]         INT              NULL,
    [GjEligible]             BIT              CONSTRAINT [DF_RiskAssessments_Audit_gj_eligible_1] DEFAULT ((0)) NULL,
    [GjEligibleNo]           BIT              CONSTRAINT [DF_RiskAssessments_Audit_gj_eligible_no_1] DEFAULT ((0)) NULL,
    [GjObtained]             BIT              CONSTRAINT [DF_RiskAssessments_Audit_gj_obtained_1] DEFAULT ((0)) NULL,
    [GjObtainedNo]           BIT              CONSTRAINT [DF_RiskAssessments_Audit_gj_obtained_no_1] DEFAULT ((0)) NULL,
    [GjDate]                 SMALLDATETIME    NULL,
    [LocationID]             INT              NULL,
    [PersonID]               INT              NULL,
    [ProgramID]              NCHAR (10)       NULL,
    [StatusTypeID]           INT              NULL,
    [SiteMgrInitials]        BIT              NULL,
    [DateCreated]            SMALLDATETIME    NULL,
    [CreatedByPersonID]      NVARCHAR (255)   NULL,
    [DateModified]           SMALLDATETIME    NULL,
    [ModifiedByPersonID]     NVARCHAR (255)   NULL,
    [AuditAction]            NVARCHAR (10)    NULL,
    [AuditDateTime]          SMALLDATETIME    CONSTRAINT [DF_RiskAssessments_Audit_AuditDateTime] DEFAULT (getdate()) NULL,
    [AuditUser]              NVARCHAR (250)   NULL,
    [AuditSQLUser]           NVARCHAR (250)   NULL,
    [GrantYear]              SMALLDATETIME    NULL,
    CONSTRAINT [PK_RiskAssessments_Audit_1] PRIMARY KEY CLUSTERED ([AuditID] ASC)
);

