CREATE TABLE [dbo].[Students_Audit] (
    [AuditID]                 INT            IDENTITY (1, 1) NOT NULL,
    [PersonID]                INT            NULL,
    [StudentTypeID]           INT            NULL,
    [SchoolAttending]         NVARCHAR (255) NULL,
    [GradeLevel]              NVARCHAR (25)  NULL,
    [PartOtherProgSchool]     BIT            NULL,
    [PartOtherProgNames]      NVARCHAR (MAX) NULL,
    [MedicalConditions]       NVARCHAR (MAX) NULL,
    [Medications]             NVARCHAR (MAX) NULL,
    [MedicalSpecialNeeds]     NVARCHAR (MAX) NULL,
    [InsuranceCompany]        NVARCHAR (255) NULL,
    [InsurancePolicyNum]      NVARCHAR (50)  NULL,
    [RideBusAlone]            BIT            NULL,
    [SignInOut]               BIT            NULL,
    [WalkHomeAlone]           BIT            NULL,
    [RideBikeHomeAlone]       BIT            NULL,
    [SignedInOutGuardOnly]    BIT            NULL,
    [ReleaseOther]            BIT            NULL,
    [ReleaseOtherText]        NVARCHAR (MAX) NULL,
    [CaseMgrStaffPersonID]    INT            NULL,
    [AuditAction]             NVARCHAR (10)  NULL,
    [AuditDateTime]           SMALLDATETIME  CONSTRAINT [DF_Students_Audit_AuditDateTime] DEFAULT (getdate()) NULL,
    [AuditUser]               NVARCHAR (250) NULL,
    [AuditSQLUser]            NVARCHAR (250) NULL,
    [InsurancePolicyGroupNum] NVARCHAR (50)  NULL,
    CONSTRAINT [PK_Students_Audit_1] PRIMARY KEY CLUSTERED ([AuditID] ASC)
);

