CREATE TABLE [dbo].[Enrollments_Audit] (
    [AuditID]               INT              IDENTITY (1, 1) NOT NULL,
    [EnrollmentID]          INT              NULL,
    [rowguid]               UNIQUEIDENTIFIER NULL,
    [DateTimeStamp]         SMALLDATETIME    NULL,
    [LastModifiedBy]        NVARCHAR (255)   NULL,
    [PersonID]              INT              NULL,
    [RiskAssessmentID]      INT              NULL,
    [EnrollmentTypeID]      INT              NULL,
    [ReferralTypeID]        INT              NULL,
    [ReferringAgencyTypeID] INT              NULL,
    [StatusTypeID]          INT              NULL,
    [ProgramID]             INT              NULL,
    [DateApplied]           SMALLDATETIME    NULL,
    [Admitted]              BIT              NULL,
    [DateAdmitted]          SMALLDATETIME    NULL,
    [DateGraduated]         SMALLDATETIME    NULL,
    [FollowUpNotes]         NVARCHAR (MAX)   NULL,
    [AuditAction]           NVARCHAR (10)    NULL,
    [AuditDateTime]         SMALLDATETIME    CONSTRAINT [DF_Enrollments_Audit_AuditDateTime] DEFAULT (getdate()) NULL,
    [AuditUser]             NVARCHAR (250)   NULL,
    [AuditSQLUser]          NVARCHAR (250)   NULL,
    [RelReasonForLeaving]   NVARCHAR (255)   NULL,
    [RelAgency]             NVARCHAR (255)   NULL,
    [RelDate]               SMALLDATETIME    NULL,
    [RecommendedBy]         NVARCHAR (250)   NULL,
    [SiteLocationID]        INT              NULL,
    [GrantYear]             SMALLDATETIME    NULL,
    CONSTRAINT [PK_Enrollments_Audit_1] PRIMARY KEY CLUSTERED ([AuditID] ASC)
);

