CREATE TABLE [dbo].[LessonPlans_Audit] (
    [AuditID]            INT              IDENTITY (1, 1) NOT NULL,
    [LessonPlanID]       INT              NULL,
    [Name]               NVARCHAR (250)   NULL,
    [rowguid]            UNIQUEIDENTIFIER CONSTRAINT [DF_LessonPlans_Audit_rowguid] DEFAULT (newid()) NULL,
    [DateTimeStamp]      SMALLDATETIME    CONSTRAINT [DF_LessonPlans_Audit_DateTimeStamp] DEFAULT (getdate()) NULL,
    [LastModifiedBy]     NVARCHAR (255)   CONSTRAINT [DF_LessonPlans_Audit_LastModifiedBy] DEFAULT ('SQL Server Management Studio') NULL,
    [LessonPlanTypeID]   INT              NULL,
    [DisciplineTypeID]   INT              NULL,
    [SiteLocationID]     INT              NULL,
    [SpecificLocationID] INT              NULL,
    [InstructorPersonID] INT              NULL,
    [AssistantPersonID]  INT              NULL,
    [StatusTypeID]       INT              NULL,
    [AgeGroupID]         INT              NULL,
    [WeekNumber]         INT              NULL,
    [Topic]              NVARCHAR (MAX)   NULL,
    [Objective]          NVARCHAR (MAX)   NULL,
    [Introduction]       NVARCHAR (MAX)   NULL,
    [Discussion]         NVARCHAR (MAX)   NULL,
    [ActivityProcedures] NVARCHAR (MAX)   NULL,
    [MaterialsNeeded]    NVARCHAR (MAX)   NULL,
    [WrapUpActivity]     NVARCHAR (MAX)   NULL,
    [ClassID]            INT              NULL,
    [ProgramID]          INT              NULL,
    [AuditAction]        NVARCHAR (10)    NULL,
    [AuditDateTime]      SMALLDATETIME    CONSTRAINT [DF_LessonPlans_Audit_AuditDateTime] DEFAULT (getdate()) NULL,
    [AuditUser]          NVARCHAR (250)   NULL,
    [AuditSQLUser]       NVARCHAR (250)   NULL,
    CONSTRAINT [PK_LessonPlans_Audit_1] PRIMARY KEY CLUSTERED ([AuditID] ASC)
);

